name: Deploy Backend and Frontend to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Build Spring Boot JAR
      run: |
         mvn clean #check
         mvn clean package -DskipTests  # Skip tests if they are failing
         ls -l target/  # Verify the JAR file is generated

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
    - name: Deploy to AWS EC2
      run: |
        echo "${{ secrets.AWS_KEY }}" > private_key.pem
        chmod 600 private_key.pem

        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} <<EOF
          cd /home/ubuntu/app
          echo "......"
          git pull origin main
          echo "......"
          docker-compose pull || true
          docker-compose build --pull
          docker-compose up -d
        EOF        
        rm -f private_key.pem  # Clean up the PEM key file
